controllers:
    resource: ../src/Controller/
    type: annotation

root_redirect_to_login:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
        path: /login
        permanent: true

kernel:
    resource: ../src/Kernel.php
    type: annotation
