# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    personnes_directory: '%kernel.project_dir%/public/uploads/personnes'
    giftlists_directory: '%kernel.project_dir%/public/uploads/giftlists'
    gifts_directory: '%kernel.project_dir%/public/uploads/gifts'
    uploads_directory: '%kernel.project_dir%/public/uploads'

    _defaults:
      bind:

services:
    # default configuration for services in *this* file
    _defaults:
      bind:
        $personnesDirectory: '%personnes_directory%'
        $giftlistsDirectory: '%giftlists_directory%'
        $giftsDirectory: '%gifts_directory%'
        $uploadsDirectory: '%uploads_directory%'

      autowire: true      # Automatically injects dependencies in your services.
      autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\EventListener\PersonneListener:
        tags :
            - {
                    name : kernel.event_listener,
                    event : personne.add,
                    method : onAddPersonneListener
            }
            - {
                  name : kernel.event_listener,
                  event : personne.list_alls,
                  method : onListAllPersonne
            }
            - {
                  name : kernel.event_listener,
                  event : personne.list_alls,
                  method : onListAllPersonne2,
                  priority : 100
            }
    App\EventListener\ExceptionListener:
        arguments:
            $urlGenerator: '@router'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority : 5 }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
#    App\Services\SendinblueMailer:
#        arguments:
#            $replyTo : 'noreply@challenge.com'

    Aws\S3\S3Client:
      arguments:
        $args:
          version: 'latest'
          region: 'eu-central-1'
          credentials:
            key: '%env(AWS_ACCESS_KEY)%'
            secret: '%env(AWS_SECRET_KEY)%'


    App\Services\UploaderService:
      arguments:
        $env: '%env(APP_ENV)%'

    App\Controller\GiftChoiceController:
      arguments:
            $envVariable: '%env(APP_ENV)%'